version: '3.4'
services:
#  Optional
#  nesys-share:
#    image: alfresco/alfresco-share:11.77
#    environment:
#      REPO_HOST: nesys-acs
#      REPO_PORT: 8080
#    ports:
#      - "8180:8080"
  nesys-acs:
    image: alfresco-content-services-nesys:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      JAVA_TOOL_OPTIONS: "-Dencryption.keystore.type=JCEKS
            -Dencryption.cipherAlgorithm=AES/CBC/PKCS5Padding
            -Dencryption.keyAlgorithm=AES
            -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
            -Dmetadata-keystore.password=mp6yc0UD9e
            -Dmetadata-keystore.aliases=metadata
            -Dmetadata-keystore.metadata.password=oKIWzVdEdA
            -Dmetadata-keystore.metadata.algorithm=AES"
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - nesys-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - nesys-postgres
  nesys-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5555:5432"
    volumes:
      - nesys-db-volume:/var/lib/postgresql/data
  nesys-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: nesys-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: nesys-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - nesys-ass-volume:/opt/alfresco-search-services/contentstore
      - nesys-ass-volume:/opt/alfresco-search-services/data
volumes:
  nesys-acs-volume:
    external: true
  nesys-db-volume:
    external: true
  nesys-ass-volume:
    external: true
